[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

# 일반적인 API 리다이렉트 규칙 - 이 규칙 하나만 남기고 나머지는 제거
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true
  
# netlify.app 도메인에서 404 페이지 리다이렉트
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200