[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "python311Packages.setuptools", "gcc"]

[phases.install]
# pip 업그레이드 명령 제거하고, 가상 환경 사용
cmds = [
  "python -m venv .venv",
  "source .venv/bin/activate && pip install -r requirements.txt"
]

[phases.build]
cmds = []

[start]
# 가상 환경에서 실행하도록 수정
cmd = "source .venv/bin/activate && uvicorn app.main:app --host 0.0.0.0 --port $PORT"