[phases.setup]
nixPkgs = ["python3", "gcc", "python3.10-pip", "python3.10-venv"]

[phases.install]
cmds = [
  "python -m venv --copies /opt/venv",
  ". /opt/venv/bin/activate && pip install -r requirements.txt"
]

[phases.build]
cmds = []  # Python 애플리케이션이라 별도의 빌드 과정은 필요 없음

[start]
cmd = "uvicorn app.main:app --host 0.0.0.0 --port $PORT" 