name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@13.209.41.149 '
            # 디렉토리 존재 확인 및 생성
            mkdir -p ~/fastube-docker
            
            # 코드 클론 또는 풀
            if [ ! -d ~/fastube-docker/.git ]; then
              # 저장소가 없으면 클론
              git clone https://github.com/jsk3342/fastube-front.git ~/fastube-docker
            else
              # 있으면 풀
              cd ~/fastube-docker && git pull
            fi
            
            # Docker 컨테이너 재시작
            cd ~/fastube-docker
            docker-compose down
            docker-compose up -d --build
          '
