name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Create deploy directory
        run: ssh -o StrictHostKeyChecking=no ubuntu@13.209.41.149 'mkdir -p ~/fastube-docker'

      - name: Check if repository exists
        id: check_repo
        run: |
          REPO_EXISTS=$(ssh -o StrictHostKeyChecking=no ubuntu@13.209.41.149 '[ -d ~/fastube-docker/.git ] && echo "true" || echo "false"')
          echo "repo_exists=$REPO_EXISTS" >> $GITHUB_OUTPUT

      - name: Clone repository if not exists
        if: steps.check_repo.outputs.repo_exists == 'false'
        run: ssh -o StrictHostKeyChecking=no ubuntu@13.209.41.149 'git clone https://github.com/jsk3342/fastube-front.git ~/fastube-docker'

      - name: Pull latest changes if repo exists
        if: steps.check_repo.outputs.repo_exists == 'true'
        run: ssh -o StrictHostKeyChecking=no ubuntu@13.209.41.149 'cd ~/fastube-docker && git pull'

      - name: Stop running containers
        run: ssh -o StrictHostKeyChecking=no ubuntu@13.209.41.149 'cd ~/fastube-docker && docker-compose down'

      - name: Start containers with latest changes
        run: ssh -o StrictHostKeyChecking=no ubuntu@13.209.41.149 'cd ~/fastube-docker && docker-compose up -d --build'

      - name: Check container status
        run: ssh -o StrictHostKeyChecking=no ubuntu@13.209.41.149 'cd ~/fastube-docker && docker-compose ps'
