name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 13.209.41.149 >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: 13.209.41.149
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # 디렉토리 생성
            mkdir -p ~/fastube-docker

            # 리포지토리 클론 또는 업데이트
            if [ ! -d ~/fastube-docker/.git ]; then
              git clone https://github.com/jsk3342/fastube-front.git ~/fastube-docker
            else
              cd ~/fastube-docker && git pull
            fi

            # Docker 컨테이너 재시작
            cd ~/fastube-docker
            docker-compose down
            docker-compose up -d --build

            # 상태 확인
            docker-compose ps
            echo "Deployment completed successfully!"
