name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Setup known hosts
        run: ssh-keyscan -H 13.209.41.149 >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: 13.209.41.149
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script_stop: true
          script: |
            # Docker 권한 설정 (처음 한번만 필요)
            if ! groups | grep -q docker; then
              echo "Docker 그룹에 사용자 추가 중..."
              sudo usermod -aG docker $USER
              echo "사용자가 Docker 그룹에 추가되었습니다. 세션 재시작이 필요할 수 있습니다."
              # 현재 세션에서 그룹 적용
              newgrp docker
            fi

            # 디렉토리 생성
            mkdir -p ~/fastube-docker

            # 리포지토리 클론 또는 업데이트
            if [ ! -d ~/fastube-docker/.git ]; then
              git clone https://github.com/jsk3342/fastube-front.git ~/fastube-docker
            else
              cd ~/fastube-docker && git pull
            fi

            # Docker 컨테이너 재시작
            cd ~/fastube-docker
            sudo docker-compose down || true
            sudo docker-compose up -d --build

            # 상태 확인
            sudo docker-compose ps
            echo "Deployment completed successfully!"
